force-app/main/default/objects/Incident__c/Incident__c.object-meta.xml
<CustomObject>
    <label>Incident</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Incident Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Incident__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>ORCA_Users__c</referenceTo>
    <relationshipLabel>Incidents (Approver)</relationshipLabel>
    <relationshipName>Incidents2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Back Office</fullName>
            </value>
            <value>
                <fullName>Front Office</fullName>
            </value>
            <value>
                <fullName>Middle Office</fullName>
            </value>
            <value>
                <fullName>External to BP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tresury Reading</fullName>
            </value>
            <value>
                <fullName>Cactus</fullName>
            </value>
            <value>
                <fullName>FVC</fullName>
            </value>
            <value>
                <fullName>3rd Party</fullName>
            </value>
            <value>
                <fullName>GEP</fullName>
            </value>
            <value>
                <fullName>GREC</fullName>
            </value>
            <value>
                <fullName>GLIGHT</fullName>
            </value>
            <value>
                <fullName>GDIST</fullName>
            </value>
            <value>
                <fullName>Global Options</fullName>
            </value>
            <value>
                <fullName>Asset</fullName>
            </value>
            <value>
                <fullName>GLPG</fullName>
            </value>
            <value>
                <fullName>JAC</fullName>
            </value>
            <value>
                <fullName>Structured Products</fullName>
            </value>
            <value>
                <fullName>GLNG</fullName>
            </value>
            <value>
                <fullName>London G&amp;P</fullName>
            </value>
            <value>
                <fullName>Financial Org Products</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Power</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Incident_Date__c.field-meta.xml
<CustomField>
    <fullName>Incident_Date__c</fullName>
    <label>Incident Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Incident_Description__c.field-meta.xml
<CustomField>
    <fullName>Incident_Description__c</fullName>
    <label>Incident Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Key_Impact__c.field-meta.xml
<CustomField>
    <fullName>Key_Impact__c</fullName>
    <label>Key Impact</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Key_Risk_Short_Title__c.field-meta.xml
<CustomField>
    <fullName>Key_Risk_Short_Title__c</fullName>
    <label>Key Risk Short Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Chicago</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Denver</fullName>
            </value>
            <value>
                <fullName>Dubai</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Jakarta</fullName>
            </value>
            <value>
                <fullName>London</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Tokyo</fullName>
            </value>
            <value>
                <fullName>Toronto</fullName>
            </value>
            <value>
                <fullName>Vancouver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Operational_Excellence_Contacts__c.field-meta.xml
<CustomField>
    <fullName>Operational_Excellence_Contacts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Operational Excellence Contacts</label>
    <referenceTo>ORCA_Users__c</referenceTo>
    <relationshipLabel>Incidents (Operational Excellence Contacts)</relationshipLabel>
    <relationshipName>Incidents3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Ops_Risk_Region__c.field-meta.xml
<CustomField>
    <fullName>Ops_Risk_Region__c</fullName>
    <label>Ops Risk Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GO-A</fullName>
            </value>
            <value>
                <fullName>GO-E</fullName>
            </value>
            <value>
                <fullName>GO-EH</fullName>
            </value>
            <value>
                <fullName>IG</fullName>
            </value>
            <value>
                <fullName>NAGP</fullName>
            </value>
            <value>
                <fullName>OpEx Central</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Recorder__c.field-meta.xml
<CustomField>
    <fullName>Recorder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Recorder</label>
    <referenceTo>ORCA_Users__c</referenceTo>
    <relationshipLabel>Incidents</relationshipLabel>
    <relationshipName>Incidents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Repeat_Incident__c.field-meta.xml
<CustomField>
    <fullName>Repeat_Incident__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Repeat Incident</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reviewer</label>
    <referenceTo>ORCA_Users__c</referenceTo>
    <relationshipLabel>Incidents (Reviewer)</relationshipLabel>
    <relationshipName>Incidents1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Risk_Category__c.field-meta.xml
<CustomField>
    <fullName>Risk_Category__c</fullName>
    <label>Risk Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>Near Miss</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Ops Risk Review</fullName>
            </value>
            <value>
                <fullName>Business Review</fullName>
            </value>
            <value>
                <fullName>Approval</fullName>
            </value>
            <value>
                <fullName>Complete Actions</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Timeline_of_Events__c.field-meta.xml
<CustomField>
    <fullName>Timeline_of_Events__c</fullName>
    <label>Timeline of Events</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORCA_Users__c/ORCA_Users__c.object-meta.xml
<CustomObject>
    <label>ORCA User</label>
    <nameField>
        <label>ORCA Users Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ORCA Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AdvancedORCASearchClass.cls
public class AdvancedORCASearchClass {
    @AuraEnabled
    public static boolean updateRecords(List<Incident__c> editedAccounts) {
        system.debug(editedAccounts);
        try{
            update editedAccounts;
            return true;
        }
        catch(Exception e) {
            system.debug(e.getMessage());
            return false;
        } 
        
    }
    
    @AuraEnabled
    public static List<Incident__c> searchWithInputs(String fromDate, String toDate, List<String> statuses, Integer rowsToDisplay, Integer offsetNumber) {
        List<Incident__c> incidents = new List<Incident__c>();
        List<String> newStatuses = new List<String>();
        if(! statuses.isEmpty() && statuses!=null) {
            for(String str:statuses) {
                newStatuses = str.split(';');
            }
        }
        
        Date fromD;
        Date toD;
        Integer rowsToDisplay1;
        Integer offsetNumber1;
        if(fromDate!=null) {
            fromD = Date.valueOf(fromDate);
        }
        if(toDate!=null) {
            toD = Date.valueOf(toDate);
        }
        if(rowsToDisplay!=null) {
            rowsToDisplay1 = Integer.valueOf(rowsToDisplay);
        }
        if(offsetNumber !=null) {
            offsetNumber1 = Integer.valueOf(offsetNumber);
        }
        
        String quer = 'SELECT Id, Name, Incident_Description__c, Timeline_of_Events__c, Incident_Date__c, Location__c, Book__c, Approver__r.Name,' 
            +'Reviewer__r.Name, Recorder__r.Name, Ops_Risk_Region__c, Operational_Excellence_Contacts__c, Area__c, Key_Impact__c, Risk_Category__c,'
            +'Key_Risk_Short_Title__c, Repeat_Incident__c, Status__c, Title__c FROM Incident__c Where Id != null ';
        
        
        If(fromDate!=null) {
            quer = quer+'and Incident_Date__c>=:fromD';
        }
        
        If(toDate!=null) {
            quer = quer+' and Incident_Date__c<=:toD ';
        }
        
        If(!newStatuses.isEmpty()) {
            quer = quer+' and Status__c IN:newStatuses';
        }
        
        IF(rowsToDisplay!=null) {
            quer = quer+' Limit :rowsToDisplay1';
        }
        IF(offsetNumber!=null) {
            quer = quer+' OFFSET :offsetNumber1';
        }
        
        system.debug('Query==='+quer);
        
        if(fromD==null && toD==null && (newStatuses.isEmpty())) {
            return incidents;
        }
        else {
            incidents = (List<Incident__c>) Database.query(quer);
            return incidents;
        }
        
    }
    
    @AuraEnabled
    public static List<Incident__c> getCountIncidents(String fromDate, String toDate, List<String> statuses) {
        List<Incident__c> incidents = new List<Incident__c>();
        List<String> newStatuses = new List<String>();
        if(! statuses.isEmpty() && statuses!=null) {
            for(String str:statuses) {
                newStatuses = str.split(';');
            }
        }
        
        Date fromD;
        Date toD;
        if(fromDate!=null) {
            fromD = Date.valueOf(fromDate);
        }
        if(toDate!=null) {
            toD = Date.valueOf(toDate);
        }
        
        String quer = 'SELECT Id FROM Incident__c Where Id != null ';
        
        
        If(fromDate!=null) {
            quer = quer+'and Incident_Date__c>=:fromD';
        }
        
        If(toDate!=null) {
            quer = quer+' and Incident_Date__c<=:toD ';
        }
        
        If(!newStatuses.isEmpty()) {
            quer = quer+' and Status__c IN:newStatuses';
        }
        
        
        system.debug('Query==='+quer);
        
        if(fromD==null && toD==null && (newStatuses.isEmpty())) {
            system.debug('No input');
            return incidents;
        }
        else {
            incidents = (List<Incident__c>)Database.query(quer);
            system.debug('Some input');	
            return incidents;
        }
    }
    
    
    
    @AuraEnabled
    public static List<String> statusPicklistValues () {
        List<String> allValues = new List<String>();
        Schema.DescribeFieldResult objDescribe = Incident__c.Status__c.getDescribe();
        //system.debug(objDescribe);
        List<Schema.PicklistEntry> ple = objDescribe.getPicklistValues();
        for(Schema.PicklistEntry p : ple){
            allValues.add(p.getLabel());
        }
        //system.debug('Available Picklists:::::::::'+allValues);	
        return allValues;
    }
    
    @AuraEnabled
    public static String updateStatusField (Id cId, String newStatus) {
        Id rId;
        String st;
        if(cId !=null){
            rId = cId;
        }
        if(newStatus !=null){
            st = newStatus;
        }
        List<Incident__c> getRecord = [Select Id, Status__c from Incident__c where Id =:rId];
        List<Incident__c> returnRecord = new List<Incident__c>();
        
        for(Incident__c inc : getRecord) {
            inc.Status__c = st;
            returnRecord.add(inc);
        }
        
        List<Database.SaveResult> results = Database.update(returnRecord, false);
        Id returnId = results.get(0).getId();
        List<Incident__c> updatedRecord = [Select Id, Status__c from Incident__c where Id =:returnId];
        String returnStatus = updatedRecord[0].Status__c;
        
        return returnStatus;
    }
    
    @AuraEnabled 
    public static Map<String, List<String>> getDependentMap(sObject objDetail, string contrfieldApiName,string depfieldApiName) {
        String controllingField = contrfieldApiName.toLowerCase();
        String dependentField = depfieldApiName.toLowerCase();
        
        Map<String,List<String>> objResults = new Map<String,List<String>>();
        
        Schema.sObjectType objType = objDetail.getSObjectType();
        if (objType==null){
            return objResults;
        }
        
        Map<String, Schema.SObjectField> objFieldMap = objType.getDescribe().fields.getMap();
        
        if (!objFieldMap.containsKey(controllingField) || !objFieldMap.containsKey(dependentField)){
            return objResults;     
        }
        
        Schema.SObjectField theField = objFieldMap.get(dependentField);
        Schema.SObjectField ctrlField = objFieldMap.get(controllingField);
        
        List<Schema.PicklistEntry> contrEntries = ctrlField.getDescribe().getPicklistValues();
        List<PicklistEntryWrapper> depEntries = wrapPicklistEntries(theField.getDescribe().getPicklistValues());
        List<String> controllingValues = new List<String>();
        
        for (Schema.PicklistEntry ple : contrEntries) {
            String label = ple.getLabel();
            objResults.put(label, new List<String>());
            controllingValues.add(label);
        }
        
        for (PicklistEntryWrapper plew : depEntries) {
            String label = plew.label;
            String validForBits = base64ToBits(plew.validFor);
            for (Integer i = 0; i < validForBits.length(); i++) {
                String bit = validForBits.mid(i, 1);
                if (bit == '1') {
                    objResults.get(controllingValues.get(i)).add(label);
                }
            }
        }
        return objResults;
    }
    
    public static String decimalToBinary(Integer val) {
        String bits = '';
        while (val > 0) {
            Integer remainder = Math.mod(val, 2);
            val = Integer.valueOf(Math.floor(val / 2));
            bits = String.valueOf(remainder) + bits;
        }
        return bits;
    }
    
    public static String base64ToBits(String validFor) {
        if (String.isEmpty(validFor)) return '';
        
        String validForBits = '';
        
        for (Integer i = 0; i < validFor.length(); i++) {
            String thisChar = validFor.mid(i, 1);
            Integer val = base64Chars.indexOf(thisChar);
            String bits = decimalToBinary(val).leftPad(6, '0');
            validForBits += bits;
        }
        
        return validForBits;
    }
    
    private static final String base64Chars = '' +
        'ABCDEFGHIJKLMNOPQRSTUVWXYZ' +
        'abcdefghijklmnopqrstuvwxyz' +
        '0123456789+/';
    
    
    private static List<PicklistEntryWrapper> wrapPicklistEntries(List<Schema.PicklistEntry> PLEs) {
        return (List<PicklistEntryWrapper>)
            JSON.deserialize(JSON.serialize(PLEs), List<PicklistEntryWrapper>.class);
    }
    
    public class PicklistEntryWrapper{
        public String active {get;set;}
        public String defaultValue {get;set;}
        public String label {get;set;}
        public String value {get;set;}
        public String validFor {get;set;}
        public PicklistEntryWrapper(){            
        }
        
    }
}